import { IconName, SUPPORTED_ICON_NAMES } from '@/constants/icon-names'
import {
  CircleUserRound,
  LucideAccessibility,
  LucideAlbum,
  LucideAnchor,
  LucideAtom,
  LucideAward,
  LucideBanana,
  LucideBarrel,
  LucideBeer,
  LucideBicepsFlexed,
  LucideBike,
  LucideBinoculars,
  LucideBird,
  LucideBone,
  LucideBot,
  LucideBottleWine,
  LucideBowArrow,
  LucideBox,
  LucideBoxes,
  LucideBrain,
  LucideBus,
  LucideCableCar,
  LucideCakeSlice,
  LucideCar,
  LucideCarFront,
  LucideCarrot,
  LucideCat,
  LucideChefHat,
  LucideChurch,
  LucideCircleUser,
  LucideCoffee,
  LucideCompass,
  LucideConstruction,
  LucideCrown,
  LucideDog,
  LucideFlameKindling,
  LucideGhost,
  LucideGlobe,
  LucideHandMetal,
  LucideLaugh,
  LucideMedal,
  LucidePartyPopper,
  LucidePlane,
  LucideRainbow,
  LucideRocket,
  LucideRockingChair,
  LucideScanFace,
  LucideSend,
  LucideSmile,
  LucideSparkles,
  LucideSprout,
  LucideStar,
  LucideTrainFront,
  LucideTreePalm,
  LucideUsers,
  LucideUsersRound,
  LucideWaves,
  LucideZap,
  type LucideIcon,
} from 'lucide-react'
import * as React from 'react'

export function IconFromName(props: {
  iconName: string
  className?: string
  fallback?: IconName
  size?: number
}): React.ReactNode {
  const stringToIcon = new Map<IconName | 'lucide:globe', LucideIcon>([
    ['lucide:users', LucideUsers],
    ['lucide:accessibility', LucideAccessibility],
    ['lucide:album', LucideAlbum],
    ['lucide:anchor', LucideAnchor],
    ['lucide:atom', LucideAtom],
    ['lucide:award', LucideAward],
    ['lucide:banana', LucideBanana],
    ['lucide:barrel', LucideBarrel],
    ['lucide:beer', LucideBeer],
    ['lucide:biceps-flexed', LucideBicepsFlexed],
    ['lucide:bike', LucideBike],
    ['lucide:binoculars', LucideBinoculars],
    ['lucide:bird', LucideBird],
    ['lucide:bone', LucideBone],
    ['lucide:bot', LucideBot],
    ['lucide:bottle-wine', LucideBottleWine],
    ['lucide:bow-arrow', LucideBowArrow],
    ['lucide:box', LucideBox],
    ['lucide:boxes', LucideBoxes],
    ['lucide:brain', LucideBrain],
    ['lucide:bus', LucideBus],
    ['lucide:cable-car', LucideCableCar],
    ['lucide:cake-slice', LucideCakeSlice],
    ['lucide:car', LucideCar],
    ['lucide:car-front', LucideCarFront],
    ['lucide:carrot', LucideCarrot],
    ['lucide:cat', LucideCat],
    ['lucide:chef-hat', LucideChefHat],
    ['lucide:church', LucideChurch],
    ['lucide:circle-user', LucideCircleUser],
    ['lucide:circle-user-round', CircleUserRound],
    ['lucide:coffee', LucideCoffee],
    ['lucide:compass', LucideCompass],
    ['lucide:construction', LucideConstruction],
    ['lucide:crown', LucideCrown],
    ['lucide:dog', LucideDog],
    ['lucide:flame-kindling', LucideFlameKindling],
    ['lucide:ghost', LucideGhost],
    ['lucide:hand-metal', LucideHandMetal],
    ['lucide:laugh', LucideLaugh],
    ['lucide:medal', LucideMedal],
    ['lucide:party-popper', LucidePartyPopper],
    ['lucide:plane', LucidePlane],
    ['lucide:rainbow', LucideRainbow],
    ['lucide:rocket', LucideRocket],
    ['lucide:rocking-chair', LucideRockingChair],
    ['lucide:scan-face', LucideScanFace],
    ['lucide:send', LucideSend],
    ['lucide:smile', LucideSmile],
    ['lucide:sparkles', LucideSparkles],
    ['lucide:sprout', LucideSprout],
    ['lucide:star', LucideStar],
    ['lucide:train-front', LucideTrainFront],
    ['lucide:tree-palm', LucideTreePalm],
    ['lucide:users-round', LucideUsersRound],
    ['lucide:waves', LucideWaves],
    ['lucide:zap', LucideZap],
    ['lucide:globe', LucideGlobe],
  ])

  const IconComponent =
    stringToIcon.get(props.iconName as IconName) ||
    (props.fallback ? stringToIcon.get(props.fallback) : undefined)
  if (!IconComponent) {
    return
  }
  // is recreated everytime, but that's fine because it holds no state
  // eslint-disable-next-line
  return <IconComponent className={props.className} size={props.size} />
}
